# this file is autogenerated by .github/workflows/update.yml
{
  url = "https://github.com/tree-sapii/nix-index-database-stable/releases/download/2026-02-08-043324/index-";
  hashes = {
    x86_64-linux = "sha256-Nw/eIvKfL2NlGT+MqV4WJ1os5T2pznai7l+h0iHlS0Q=";
    aarch64-linux = "sha256-mRYIluqnqL+XaJTi2rBK79AZjBypxeXCQx2uQVRq4YE=";
    x86_64-darwin = "sha256-htstfXTC4yAhYnWFeIssw3ozm+j+igxgw46mDXLbNYA=";
    aarch64-darwin = "sha256-KeIBG1dcbOkqNnSGBZY+rG4zqajrK1b8JZbcKhpWpQ0=";
  };
}
