# this file is autogenerated by .github/workflows/update.yml
{
  url = "https://github.com/tree-sapii/nix-index-database-stable/releases/download/2026-03-01-042400/index-";
  hashes = {
    x86_64-linux = "sha256-Vie3CFSTa+THvspuJX/DKk/xzOh/oIqj1laK5q0Qbj4=";
    aarch64-linux = "sha256-ZVak4WvTecQalOnF+8vKAi28o8JNYPEtHxIloSHuoA8=";
    x86_64-darwin = "sha256-BZUtjcpYMAEA1q64eaOh67cA++5BOLWAoXWHGCWrN8M=";
    aarch64-darwin = "sha256-50FhWffQp53kol7W1R0OIOKYqmUWJGxDfb2P+3RMPhM=";
  };
}
