# this file is autogenerated by .github/workflows/update.yml
{
  url = "https://github.com/tree-sapii/nix-index-database-stable/releases/download/2026-03-08-041229/index-";
  hashes = {
    x86_64-linux = "sha256-CyoAMPisEZHt/HTBnaxjxQ/jAkOjcHSJ/AbgBNW8jYU=";
    aarch64-linux = "sha256-hDK4E1W71boJm7ja68NwoTJMyTKb+mJSitXJ70HUg70=";
    x86_64-darwin = "sha256-acCvoUZQ7BUqzMxvAOTg+vVwuLJKaBPjMeaF5o6ImYw=";
    aarch64-darwin = "sha256-zj32AU1N8rUEDglSme1jUMeSHjviHvOHUlis+5sDMxE=";
  };
}
